### ISSUE TITLE
开机禁行 卡EB

### ISSUE THREAD

**Issue by Xuedingzheng** [raycool/Gigabyte-Z390-Gaming-X-Hackintosh-I7-9700K-SAPPHIRE-5500XT#1]
我的是和你同款主板，9700 + 5700XT超白金，但是我开机禁行，怎么回事

**Comment by raycool** [comment]
BIOS中cfg lock 这个关闭了吗？
没关闭会卡EB

**Comment by Xuedingzheng** [comment]
> BIOS中cfg lock 这个关闭了吗？
> 没关闭会卡EB

关闭了的

**Comment by raycool** [comment]
完全复用的这个EFI么？按说不应该有问题的。
方便可以发一份EFI周末比对下，或者我在我电脑上测试一下。

**Comment by Xuedingzheng** [comment]
我是直接把你的EFI放进去用的，没有做任何修改，我的主板和你一样，9700 + 5700 XT,按道理应该不用做修改吧，我10.15.3的时候是可以进去的，但是我升级成10.15.4后就进不去了。我的bios是官方的f10c版本，用论坛的方法将cfg关闭了。

**Comment by raycool** [comment]
按说是不用做任何修改的，我也升级了，中间15.4的补充更新也更新了，一直也没问题。
我把这个EFI放U盘里面引导试了试，也是没问题的，可以直接进。
你试试使用U盘引导，要么就更换最新的OC版本试试，使用最新的驱动和配置文件。
