### ISSUE TITLE
主板usb 3.1的口未能识别外置移动硬盘

### ISSUE THREAD

**Issue by etscript** [raycool/Gigabyte-Z390-Gaming-X-Hackintosh-I7-9700K-SAPPHIRE-5500XT#2]
根据最新分支，CFG lock 关闭之后，修改了config里面两个配置。
Config—–NVRAM—–LegacyOverwrite   False  （原本是True）
Config—–Misc—–Security——ExposeSensitiveData  2（2原生nvram，3模拟nvram，原本这里是3）

发现主板usb 3.1的口未能识别外置移动硬盘。（绿联 ssd 移动硬盘盒，pm981a ssd）

**Comment by etscript** [comment]
你好，你的usb3.1 好用吗？我的主板bios是 官方F9，还未使用你的bios版本。

除了usb 3.1 其他完美。
配置 U: i9 主板:z390 gaming x 显卡:rx580 内存:海盗船 16X2 3200  SSD: 西数sn750 500G

**Comment by raycool** [comment]
确实这两个配置的错了，多谢指点。
usb3.1这个确实不能识别，应该是USB内建的问题，当时我只试了USB3的端口，没测试这个3.1 应该是漏掉内建了。
等晚点修复下。

**Comment by raycool** [comment]
重新定制了下3.1 应该可以用了
mac貌似有15个USB端口限制，会有几个USB口可能不能用的情况。

**Comment by etscript** [comment]
opencore的usb定制也是用hackintool吗？我现在插上去那些口没动静，我不知道是对应哪个usb。我是要先换成inject all的，然后再开始定制吗？或者。。。坐等白嫖，嘿嘿。

**Comment by raycool** [comment]
嗯，我已经重新定制了。你下载试试。

**Comment by etscript** [comment]
好滴。我看更新了usb和whatevergreen。1、usb定制是怎么定制的呀？能分享下教程吗？2、这次更新whatevergreen 也是因为usb的原因吗？

**Comment by raycool** [comment]
不是，以前用的魔改直接使核显满载1.2ghz，现在用的没有魔改的，config的boot args里加个命令可以核显满载。魔改的版本有些老了。
USB是使用hackintool定制的，网上搜索下就行，也比较简单。

**Comment by etscript** [comment]
感谢

**Comment by etscript** [comment]
usb3.1没问题了。这个版本的oc，升级10.15.5 内测版也没问题，估计下个版本可以直接升。

**Comment by leixjin** [comment]
你好，你们有没有遇到过 csm 关闭之后开机 logo 花屏的情况？不知道跟显卡有没有关系，我的是 RX590

**Comment by raycool** [comment]
> 你好，你们有没有遇到过 csm 关闭之后开机 logo 花屏的情况？不知道跟显卡有没有关系，我的是 RX590

没有遇到这个问题
应该是分辨率设置的问题吧
调整下配置文件中的分辨率设置试试。
