### ISSUE TITLE
启动异常，卡EB

### ISSUE THREAD

**Issue by SeptemberHX** [raycool/Gigabyte-Z390-Gaming-X-Hackintosh-I7-9700K-SAPPHIRE-5500XT#4]
配置也是 Z390 gaming x + 9700k + 5500xt，系统 10.15.7，BIOS F10h，CFG 已关闭

一开始的时候是好使的，直接替换原本的 clover 就行了，能够正常进系统之类的。
然后我尝试升级了 Big Sur，最后的安装升级界面会直接崩溃，所以我就通过备份回到了之前的备份。
然后再用这个EFI启动，就出现下面的问题了，不知道为啥。。

![IMG_20201114_174203](https://user-images.githubusercontent.com/18042424/99144630-6ff7cb80-26a2-11eb-87e1-9cb2a541f993.jpg)

**Comment by raycool** [comment]
这个问题不是很清楚，看起来像是CFG的锅，但是我这又测试了下没问题。
