### ISSUE TITLE
老哥，你好bios的设置你可以更新下路径吗？有几个一直找不到。

### ISSUE THREAD

**Issue by user1121114685** [raycool/Gigabyte-Z390-Gaming-X-Hackintosh-I7-9700K-SAPPHIRE-5500XT#5]
有好几个一直找不到，另外可以把项目里面的bios删了。

**Comment by user1121114685** [comment]
csm 关闭。在boot 下 GSM support 选择disabled。  
vt-d 关闭（个人认为可以不关闭）
fast boot 关闭。 在boot 下 fast boot 选择disabled。  
Above 4G decoding 开启，在settings下 io ports下 Above 4G decoding选择 enabled。  
EHCI handoff 开启，在settings下选择usb configuration下XHCI hand-off 选择enabled。  
CFG lock 关闭，在boot下选择 CFG lock 选择 disabled。  
serial ports 关闭，在settings下super io configuration下serial port选择 disabled。

**Comment by raycool** [comment]
好的，项目里面的bios确实可以删除了。
