### ISSUE TITLE
非常感谢大佬提供的EFI文件

### ISSUE THREAD

**Issue by MorKe9986** [raycool/Gigabyte-Z390-Gaming-X-Hackintosh-I7-9700K-SAPPHIRE-5500XT#6]
有几个小问题想请教一下大佬：
我的配置是8700K+RX590的，需要修改哪些地方？
大佬有技术群吗？我想入群，不懂黑苹果的进阶玩法，想学习

**Comment by raycool** [comment]
应该只需要修改CPU的核显ID和显卡的fbname相关内容。
其他差异不是很大
没有群呢，都是看文档和论坛以及别人的教程摸索出来的~

**Comment by luhua98989898** [comment]
我的没独显 只有核显可以用吗？核显可以加速吗

**Comment by luhua98989898** [comment]
我是i5 9600k 没有独显 可以用这个吗？核显可以加速吗

**Comment by raycool** [comment]
可以吧，删除独显的那些配置条目就行。
